### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Suntrie** [AHXPLAY/JavaClassProject#2]
1. Возвращать коллекции принято через использование интерфейсов, а не тех реализаций, которые используются внутри класса/ метода (используя интерфейсы, Вы "подписываете обязательство" на то, что возвращаемая коллекция должна реализовывать только часть методов, которыми обладает  коллекция, на данный момент реально используемая в реализации - и внешние "клиенты", которым Вы её вернёте, могут рассчитывать только на эти методы. Таким образом, внутри своего метода Вы потом можете менять коллекцию, например, на другие виды, удовлетворяющие интерфейсу - а в использующем коде при этом менять ничего не придётся). Поля также обычно объявляются с применением интерфейсов;
2. Для всех методов типа set/remove видимо, стоит возвращать булево значение, чтобы программист, использующий Ваш код, мог понять, каковы результаты вызова, выполнилось ли то, чего он хотел;
3. Повторяющиеся фрагменты кода вроде
`  if (index >= libraryList.size() || index < 0) return false;` лучше вынести во вспомогательную функцию (код будет легче читать/ модифицировать). Кроме этого, ряд существующих методов можно переиспользовать в реализации соседних, из тех же соображений;
4. В некоторых публичных методах в текущей версии кода можно получить NPE (видимо, стоит добавить дополнительные чекеры). В частности, в equals - который может быть автосгенерирован средствами Идеи (также, как и override других стандартных методов);
5. В целом, многое из того, что реализовано, более компактно можно описать с помощью Stream API - просьба попробовать его использовать хотя бы для некоторых методов.

**Comment by AHXPLAY** [comment]
второй пункт в меня реализован уже в методах changeBook и deleteBook, а остальные замечания учту.

**Comment by Suntrie** [comment]
1. Пока актуально для таких публичных методов, как findAllByName и др. Что будет с ними, если Ваш класс переедет на реализацию на основе другого вида списков (например, вставка в начало LinkedList сильно дешевле, чем для ArrayList, и для Вашего кода именно такой юзкейс является актуальным)? Как правило, публичные методы классов стараются проектировать так, чтобы стоимость (время/сложность) изменений в случае потенциальной модификации была минимальной. **Important:** Вам здесь точно нужно [наследование, а не композиция](https://habr.com/ru/post/325478/)? Все ли публичные методы, которые Вы унаследовали, действительно нужны и должны быть доступны для библиотеки, например? Нельзя с их применением как-либо испортить данные? Кроме этого, с содержательной точки зрения "Слой предметной области не должен знать, как у нас там все внутри сделано" - наследование, как правило, про иерархию моделей предметной области. А завязываясь на конкретные классы реализации библиотеки, Вы утверждаете, что эта модель обладает дополнительными свойствами - например, всегда лежит в памяти как массив (что реальности может не соответствовать и при этом логическим нарушением являться не будет). Кроме этого, классы (в том числе, стандартные коллекции) меняются, что-то становится Deprecated, как Vector, что потенциально может привести к проблемам при переезде между различными версиями JDK;
2. Ок
3. Ок, хотя, кажется, с логикой проверки isIndexIncorrect пока что-то частично пошло не так
4. Пока не совсем согласна. Что будет с vararg-параметром, null collection?
5. +
_______
6. Попробуйте, пожалуйста, воспользоваться equals library в рамках тестов (его, видимо, нужно починить)

**Comment by Suntrie** [comment]
1. Согласна
2. +
3. +
4. +
5. +
6. this.hashCode() == library.hashCode() - посмотрите, пожалуйста, что такое коллизии хэш-функций, и поясните в двух словах в ответном сообщении (код, видимо, также придётся немного скорректировать);
7. JFYI - станадартные override-ы методов можно просто генерировать: Code -> generate -> equals and hashcode, например;
8. Minor. Для deleteBook в текущей реализации вроде indexOf тоже вполне подходит;
9. `list.stream().filter(book -> isSubstringContains(book.getName(), name) &&
                isSubstringContains(book.getAuthor(), author) &&
                isSubstringContains(book.getGenre(), genre) &&
                isSubstringContains(book.getShelf(), shelf)).forEach(resultList::add);` - вполне годный вариант, но здесь чаще встречается вынос под return (без заведения общей переменной) с .collect(Collectors.toList()) или чего-то подобного;
10. Копипасту в findByParams/ findAllByParams стоит вынести в общий приватный метод (правой кнопкой мыши -> Refactor -> Extract method);
11. return optional.orElse(null); - под return-ом, в среднем, лучше выдавать сам Optional (по тем же причинам, по которым вместо null в случае с возвращаемым значением-коллекцией лучше выдавать пустую коллекцию - меньше проверок). Пользоваться таким результатом сравнительно удобно можно так (например): optional.ifPresent(it->it.getShelf());
12. Пока не везде хватает тестов
![Uploading Screenshot 2021-02-21 at 00.15.26.png…]()

**Comment by AHXPLAY** [comment]
6. Коллизии хэш функций это когда для разных объектов хэш одинаков
